config/routes.rb
Yehkevin::Application.routes.draw do

  scope '(:locale)' do

match '/member', to: 'users#index'
 	devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
	resources :abouts
	resources :companies
	resources :customers
  resources :products
	resources :carts
	match '/contact', to: 'home#contact'
	resources :orders
  resources :news
	resources :line_items
	resources :categories
	match '/search' => 'products#search'
	root to: 'home#index', as: 'home'
	end

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content, :image, :title, :image_cache,:sorts_attributes
	mount_uploader :image, ImageUploader
	has_many :sorts
	accepts_nested_attributes_for :sorts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :line_items, dependent: :destroy
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity +=1
		else
			current_item = line_items.build(product_id: product_id)
		end
			current_item
	end

	def total_items
		line_items.sum(:quantity)
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
	has_many :tags
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :content, :image, :title, :image_cache
	mount_uploader :image, ImageUploader
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
	belongs_to :cart
	belongs_to :order
	belongs_to :product
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :tag_id
	belongs_to :tag
	has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type, :phone
	has_many :line_items, dependent: :destroy
	has_many :products,through: :line_items
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :product_id, :image_cache
	belongs_to :products
	mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :content, :list_id, :number, :title, :pictures_attributes, :videos_attributes
	belongs_to :list
	has_many :pictures
	has_many :videos
	has_many :line_items
	has_many :order, through: :line_items
	accepts_nested_attributes_for :pictures, :videos



end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :category_id, :name
	has_many :lists
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :product_id, :video, :video_cache
	belongs_to :product
	mount_uploader :video, VideoUploader
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order("id desc").paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
		@cart = current_cart
		@companies = Company.order("id desc").paginate(page: params[:id], per_page: 5)
	end
def contact
end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_company_list.html.erb
<table class="table">
<% companies.each do |com| %>
<tr>
<td><%= time_ago_in_words(com.created_at) %>前</td>
<td><%= link_to com.title, company_path(com.id) %></td>

</tr>
<% end %>
</table>

app/views/companies/_form.html.erb
<%= form_for(@company, html: { multipart: true}) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>
<%= render partial: 'companies/company_list', locals: {companies: @companies} %>
<%= will_paginate @companies %>
<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @company.title %>
</p>

<p>
  <b>Content:</b>
  <%= @company.content %>
</p>

<p>
  <b>Image:</b>
  <%= @company.image %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>