config/routes.rb
Yehkevin::Application.routes.draw do

  scope '(:locale)' do

match '/member', to: 'users#index'
 	devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
	resources :abouts
	resources :companies
	resources :customers
  resources :products
	resources :carts
	match '/contact', to: 'home#contact'
	resources :orders
  resources :news
	resources :line_items
	resources :categories
	match '/search' => 'products#search'
	root to: 'home#index', as: 'home'
	end

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content, :image, :title, :image_cache,:sorts_attributes
	mount_uploader :image, ImageUploader
	has_many :sorts
	accepts_nested_attributes_for :sorts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :line_items, dependent: :destroy
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity +=1
		else
			current_item = line_items.build(product_id: product_id)
		end
			current_item
	end

	def total_items
		line_items.sum(:quantity)
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
	has_many :tags
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :content, :image, :title, :image_cache
	mount_uploader :image, ImageUploader
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
	belongs_to :cart
	belongs_to :order
	belongs_to :product
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :tag_id
	belongs_to :tag
	has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type, :phone
	has_many :line_items, dependent: :destroy
	has_many :products,through: :line_items
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :product_id, :image_cache
	belongs_to :products
	mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :content, :list_id, :number, :title, :pictures_attributes, :videos_attributes
	belongs_to :list
	has_many :pictures
	has_many :videos
	has_many :line_items
	has_many :order, through: :line_items
	accepts_nested_attributes_for :pictures, :videos



end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :category_id, :name
	has_many :lists
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :product_id, :video, :video_cache
	belongs_to :product
	mount_uploader :video, VideoUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
		@cart = current_cart
		@companies = Company.order("id desc").paginate(page: params[:id], per_page: 5)
	end
def contact
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
		@cart = current_cart
		unless params[:t]
			@products = Product.order("id desc").paginate(page: params[:page], per_page: 24)
		else 
			@products = Product.where("list_id = ?", params[:t]).order("id desc").paginate(page: params[:page], per_page: 24)
		end
		@products.each do |product|
			product.pictures.build
		end
	end

	def search
		@products = Product.where("title like ? or number like ?", 
															'%'+params[:q]+'%','%'+params[:q]+'%').order("id desc").paginate(page: params[:page], per_page: 12)
	end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
		3.times{@product.pictures.build}
		@product.videos.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {multipart: true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
		<%= f.label :content %><br />
		<%= javascript_include_tag "ckeditor/ckeditor.js" %>  
    <%= f.cktext_area :content %>
  </div>
  <div class="field">
		<%= f.fields_for :pictures do |pic| %>
			<%= pic.label :imag %>
			<%= pic.file_field :image %>
		<% end %>
  </div>
	<div class="field">
		<%= f.fields_for :videos do |video| %>
			<%= video.label :video %>
			<%= video.file_field :video %>
		<% end %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_list.html.erb
<% products.each do |product| %>
	<%=link_to image_tag(product.pictures.first.image_url), product %>
	<b>	<%= product.title %></b>
	<b>	<%= product.number %></b>
<% end %>

app/views/products/_nav_list.html.erb
	<nav class="nav-drop">
		<h3>分类导航</h3>
			 <ul>
				 <li>
				 <% Category.all.each do |cate| %>
					 <%=link_to  cate.name, category_path(cate.id) %>
				 
				 <ul>
					 <% cate.tags.each do |tag| %> 
						 <li><%= link_to tag.name, category_path(tag.id) %><br />
						 <% tag.lists.each do |list| %>
							 <%= link_to list.name, products_path(t:list) %>
						 <% end %>
					 <% end %>
				 <% end %>
							 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a> <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>

					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>

				 </ul>
				 </li>
				 <li>
				 <a href="#">搬运设备</a>
				 <ul>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>

				 </ul>
				 </li>
				 <li>
				 <a href="#">搬运设备</a>
				 <ul>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>

				 </ul>
				 </li>
				 <li>
				 <a href="#">搬运设备</a>
				 <ul>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>

				 </ul>
				 </li>
				 <li>
				 <a href="#">搬运设备</a>
				 <ul>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>
					 <li><a href="#">油桶搬运设备</a><br />
					 <a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a><a href="#">油桶夹</a>
					 </li>

				 </ul>
				 </li>


			 </ul>
		</nav>	

app/views/products/_show_product.html.erb

<div class="p-data">
	<div class="data-gallery" style="position:relative;">
		<div id="idViewer2" class="izViewer2"></div>
		<div id="data-pic" class="data-pic" >
			<img id="idImage2" class="izImage2" />		
		</div>
		<div class="thumbsPanel">
			<a href="javascript:void(0);" class="prev"></a>
			<div class="thumbsItems">
				<ul id="pic-thumbs" class="thumbsList list">

				</ul>
			</div>
			<a href="javascript:void(0);" class="next"></a>
			<div id="idHandle3" class="handle2"></div>
		</div>
	</div>
</div>
<script>
$(function(){
	//图片切换和放大的效果
	var iz = new ImageZoom( "idImage2", "idViewer2", {
		mode: "handle", handle: "idHandle3"
	});
	var arrPic = [], 
		list = $$("pic-thumbs");
<% @product.pictures.each do |pic| %>
	arrPic.push({ smallPic: "<%= pic.image_url(:small_thumb) %>", originPic: "<%= pic.image_url(:thumb) %>", zoomPic: "<%= pic.image_url(:big) %>" });
	
<% end %>

	$$A.forEach(arrPic, function(o, i){
		var li = list.appendChild(document.createElement("li"));
		var img = li.appendChild(document.createElement("img"));
		img.src = o.smallPic;
		img.onmouseover = function(){
			iz.reset({ originPic: o.originPic, zoomPic: o.zoomPic });
			$$A.forEach(list.getElementsByTagName("img"), function(img){ img.className = ""; });
			this.className = "on";
		}
		if(!i){ img.onmouseover(); }
	});
	//小图左右移动
	var pic_obj = $("#pic-thumbs"),
		obj = pic_obj.find('li');
	$(".prev").addClass('disabled');
	if(obj.length<=4){$(".next").addClass('disabled');}
	$("body").data("eqindex", 0);
	$(".prev").click(function(){
		var eqindex = $("body").data("eqindex");
		if(eqindex*4>0){
			pic_obj.animate({left:"+="+(obj.width()+4)*4+"px"}, 500);
			$("body").data("eqindex", eqindex-1);
			$(".next").removeClass('disabled');
			if((eqindex-1)==0){
				$(this).addClass('disabled');
			}
		}
	});
	$(".next").click(function(){
		var eqindex = $("body").data("eqindex");
		if(eqindex*4<(obj.length-4)){						
			pic_obj.animate({left:"-="+(obj.width()+4)*4+"px"}, 500);
			$("body").data("eqindex", eqindex+1);
			$(".prev").removeClass('disabled');
			if((eqindex+1)==Math.ceil(obj.length/4)-1){
				$(this).addClass('disabled');
			}
		}
	});
});
</script>


app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'carts/list_cart' %>
<h1 style="margin-top: 10px">Listing products</h1>

<p>
<%= l Time.now,:format => :long  %>
</p>
<% Category.all.each_with_index do |cate, index| %>
	<%= link_to cate.name, home_path(cate.id) %>
	<% cate.tags.each do |tag| %>
		<%= link_to tag.name, category_path(tag.id) %>
		<% tag.lists.each do |list| %>
			<%= link_to list.name, products_path(t:list) %>
		<% end %>
	<% end %>
<% end %>
<%= render partial: 'products/list', locals: {products: @products} %>
<%= will_paginate @products %>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="margin-top: 30px">
		<%= render partial: "common/product_list", locals: { products: @products } %>
	</div>

app/views/products/show.html.erb
		<aside>
		<div class="bananer">
			<%= link_to t('.edit'), edit_product_path(@product) %>
			|<%= link_to t('.destroy'), product_path(@product), method: :delete, data: {confirm: "确定删除吗？"} %>
		</div>
		<div class="nav-list">
			<%= render "products/nav_list" %>	
			<div class="list">
				<div class="title-product"
					<p><%= @product.title %>
						<%= button_to t('.addcart'), line_items_path(product_id: @product), class: "btn btn-info" %>
						</p>
				</div>
			<div class="picture-product">
				<%= render 'products/show_product' %>
			</div>
			<div class="desc-product">
				<%= @product.number %>
			</div>
			<div class="content-product">
				<div id="tabbox">
					<ul class="tabs" id="tabs2">
						<li><a href="#"><%= t('.descript') %></a></li>
						<li><a href="#"><%= t('.detail') %></a></li>
						<li><a href="#"><%= t('.video') %></a></li>
						<li><a href="#"><%= t('.service') %></a></li>
					</ul>
					<ul class="tab_conbox" id="tab_conbox2">
						<li class="tab_con">
						<p>dasd</p>
<p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p><p>dasd</p>
						</li>
						<li class="tab_con">
						<%= raw @product.content %>
						</li>
						<li class="tab_con">
						<% @product.videos.each do |video| %>
							<%=video_tag video.video_url, :size => "420x340", :controls => true %>
						<% end %>
						</li>
						<li class="tab_con">
						<img src="image/4.jpg" />
						<img src="image/7.jpg" />
						<img src="image/8.jpg" />
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="right-product">
			<h3><%= t('.recommend') %></h3>
			<% Product.limit(2).all.each do |product| %>
				<div class="recommend">
					<% product.pictures.limit(1).each do |pic| %>
						<%= link_to image_tag(pic.image_url(:normal)), product %> 
					<% end %>
					<b><%= product.title %></b>
					<b><%= product.number %></b>
				</div>
			<% end %>
		</div>
		</aside>
		<footer>
		dasd
		</footer>
<script type="text/javascript">
$(document).ready(function() {
	jQuery.jqtab = function(tabtit,tab_conbox,shijian) {
		$(tab_conbox).find("li").hide();
		$(tabtit).find("li:first").addClass("thistab").show(); 
		$(tab_conbox).find("li:first").show();
		$(tabtit).find("li").bind(shijian,function(){
			$(this).addClass("thistab").siblings("li").removeClass("thistab"); 
			var activeindex = $(tabtit).find("li").index(this);
			$(tab_conbox).children().eq(activeindex).show().siblings().hide();
			return false;
		});
	};

	/*调用方法如下：*/
	$.jqtab("#tabs2","#tab_conbox2","click");
});
</script>

app/views/products/show.html1.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Number:</b>
  <%= @product.number %>
</p>

<p>
  <b>Content:</b>
  <%= @product.content %>
</p>
<%= render 'show_product' %>

<%= link_to 'shanchu', product_path, method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>